# Generated by Django 4.2.5 on 2023-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('city', models.CharField(max_length=100)),
                ('max_temp', models.CharField(max_length=100)),
                ('min_temp', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time_fetched', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Weather',
            },
        ),
    ]
