# Generated by Django 5.0.7 on 2024-07-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('max_temp', models.CharField(max_length=100)),
                ('min_temp', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date_time_fetched', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Weather',
            },
        ),
    ]
